// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:256780f8-96f2-4f88-a811-a4b4bc3c1a26",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_DtgFGBTZv",
    "aws_user_pools_web_client_id": "6k7hcest2lu5m9a2ebh6c0qug9",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://vcn6luv4gzedxbmrferkhn5fgq.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
